#!/usr/bin/env python3
"""Assemble web/template.html + data/build.json + web/coast.min.json -> dist/index.html (FR) and dist/en/index.html (EN).

One template, two outputs: the FR path stays byte-for-byte the same generation logic as before
(only additions are the hreflang links and the language switch, which the template now carries
statically). The EN path additionally runs an ordered list of (french, english) string
replacements against the static HTML (everything before <script>); each french string is
asserted present so a future template edit can't silently leave French text in the EN page.
Dynamic sentences generated by JS branch at runtime on the injected `const LANG` via the
template's own `L(fr, en)` helper -- see web/template.html.
"""
import json, os, shutil

root = os.path.dirname(os.path.abspath(__file__))

CANONICAL_FR = "https://oceandataconsulting.fr/climate-observer"
CANONICAL_EN = "https://oceandataconsulting.fr/en/climate-observer"

LANGSWITCH_FR = '<span class="langswitch"><b>FR</b> · <a href="%s">EN</a></span>' % CANONICAL_EN
LANGSWITCH_EN = '<span class="langswitch"><a href="%s">FR</a> · <b>EN</b></span>' % CANONICAL_FR

# Ordered (french, english) replacement pairs applied to the static HTML (head portion,
# i.e. everything before <script>) for the EN build. Order matters where one pattern is a
# substring of another (longer/more-specific patterns first).
PAIRS_EN = [
    ('<html lang="fr">', '<html lang="en">'),
    ('<title>Climate Observer, l\'écart à la normale, jour après jour</title>',
     '<title>Climate Observer, ocean and land temperature anomalies, day by day</title>'),
    ('rel="canonical" href="%s">' % CANONICAL_FR, 'rel="canonical" href="%s">' % CANONICAL_EN),
    ('property="og:url" content="%s">' % CANONICAL_FR, 'property="og:url" content="%s">' % CANONICAL_EN),
    ('content="Écart à la normale des océans et des continents, mis à jour chaque jour : globe, prévision 9 jours, El Niño, glace de mer, coraux.">',
     'content="Ocean and land temperature anomalies, updated every day: globe, 9-day forecast, El Niño, sea ice, corals.">'),
    ('property="og:image:alt" content="Carte mondiale de l\'écart de température à la normale, Climate Observer">',
     'property="og:image:alt" content="World map of ocean and land temperature anomalies, Climate Observer">'),
    ('property="og:locale" content="fr_FR">', 'property="og:locale" content="en_GB">'),
    # brand bar / footer links -> EN home
    ('href="https://oceandataconsulting.fr" target="_blank" rel="noopener"><span class="brandbar-dot"></span>',
     'href="https://oceandataconsulting.fr/en" target="_blank" rel="noopener"><span class="brandbar-dot"></span>'),
    ('href="https://oceandataconsulting.fr" target="_blank" rel="noopener">OceanData Consulting</a>',
     'href="https://oceandataconsulting.fr/en" target="_blank" rel="noopener">OceanData Consulting</a>'),
    ('href="https://oceandataconsulting.fr/#contact" target="_blank" rel="noopener">Contact</a>',
     'href="https://oceandataconsulting.fr/en/contact" target="_blank" rel="noopener">Contact</a>'),
    ('<!--LANGSWITCH-->', LANGSWITCH_EN),
    # static number placeholders (overwritten by JS on load, but a no-JS crawler sees these)
    ('id="gnum">+0,00 °C<', 'id="gnum">+0.00 °C<'),
    ('id="landMean">+0,0 °C<', 'id="landMean">+0.0 °C<'),
    ('id="trend30">+0,00<', 'id="trend30">+0.00<'),
    ('id="lbig">+0,0<small>°C</small><', 'id="lbig">+0.0<small>°C</small><'),
    ('id="enum">+0,0 °C<', 'id="enum">+0.0 °C<'),
    ('id="e4">+0,0 °C<', 'id="e4">+0.0 °C<'),
    ('id="e3">+0,0 °C<', 'id="e3">+0.0 °C<'),
    ('id="e12">+0,0 °C<', 'id="e12">+0.0 °C<'),
    ('id="eoni">+0,0 °C<', 'id="eoni">+0.0 °C<'),
    # nav tabs
    ('<button data-tab="globe" aria-pressed="true">Le globe</button><button data-tab="enso" aria-pressed="false">El Niño en direct</button>',
     '<button data-tab="globe" aria-pressed="true">The globe</button><button data-tab="enso" aria-pressed="false">El Niño live</button>'),
    # globe tab header
    ('<div class="kicker">Océans et continents, écart à la normale</div>',
     '<div class="kicker">Oceans and land, departure from normal</div>'),
    ('<h1 id="headline">Aujourd\'hui, l\'océan est à ', '<h1 id="headline">Today, the ocean is '),
    (' au-dessus de sa normale.</h1>', ' above its normal.</h1>'),
    ('<p class="sub" id="sublead">Moyenne des océans entre 60°S et 60°N, et <span id="lmeanTxt">les terres sont à +0,00 °C</span>. Chaque pixel compare la température du jour à celle attendue ce jour-là. Faites tourner le globe, touchez chez vous.</p>',
     '<p class="sub" id="sublead">Average of the oceans between 60°S and 60°N, and <span id="lmeanTxt">land is at +0.00 °C</span>. Each pixel compares the day\'s temperature with what is expected on that date. Spin the globe, touch where you live.</p>'),
    ('<span>de l\'océan à plus de +1 °C</span>', '<span>of the ocean above +1°C</span>'),
    ('<span>écart moyen sur les continents</span>', '<span>average departure over land</span>'),
    ('<span>évolution sur 30 jours</span>', '<span>change over 30 days</span>'),
    ('aria-label="Lancer l\'animation">▶</button>', 'aria-label="Play animation">▶</button>'),
    ('aria-label="Jour affiché">', 'aria-label="Day shown">'),
    # local ("et chez vous") block
    ('<h2 id="ltitle">Et chez vous ?</h2>', '<h2 id="ltitle">And where you live?</h2>'),
    ('<p id="lhelp">Touchez un point sur le globe, mer ou terre, ou utilisez votre position.</p>',
     '<p id="lhelp">Touch a point on the globe, ocean or land, or use your location.</p>'),
    ('<span id="sdmid">écart quotidien, 30 jours</span>', '<span id="sdmid">daily anomaly, 30 days</span>'),
    ('<button class="geo" id="geo">Utiliser ma position</button>', '<button class="geo" id="geo">Use my location</button>'),
    # surveillance block (static skeleton)
    ('<h2>Surveillance des océans</h2>', '<h2>Ocean monitoring</h2>'),
    ('<h3>Glace de mer</h3>', '<h3>Sea ice</h3>'),
    ('<p>La banquise vue du dessus des pôles, comparée au même jour d\'une année passée. Choisissez l\'année :</p>',
     '<p>Sea ice viewed from above the poles, compared with the same date in a past year. Choose the year:</p>'),
    ('<p class="fine"><span class="swatch" style="background:#eef4f8;margin-left:0"></span>glace les deux années <span class="swatch" style="background:#ff8a4c"></span>glace le <span class="refy">1982</span>, disparue aujourd\'hui <span class="swatch" style="background:#6fd0ff"></span>glace aujourd\'hui, absente le <span class="refy">1982</span></p>',
     '<p class="fine"><span class="swatch" style="background:#eef4f8;margin-left:0"></span>ice both years <span class="swatch" style="background:#ff8a4c"></span>ice on <span class="refy">1982</span>, gone today <span class="swatch" style="background:#6fd0ff"></span>ice today, absent on <span class="refy">1982</span></p>'),
    ('<p class="fine">Carte : concentration de glace OISST (≥ 15 %). Chiffres : NSIDC Sea Ice Index, normale 1991-2020.</p>',
     '<p class="fine">Map: OISST ice concentration (≥ 15%). Figures: NSIDC Sea Ice Index, 1991-2020 normal.</p>'),
    # ENSO tab
    ('<div class="kicker">Pacifique équatorial, la zone qui fait la météo du monde</div>',
     '<div class="kicker">Equatorial Pacific, the region that shapes the world\'s weather</div>'),
    ('<h1 id="ehead">Le thermomètre d\'El Niño est à ', '<h1 id="ehead">The El Niño thermometer is at '),
    (' aujourd\'hui.</h1>', ' today.</h1>'),
    ('<div class="next"><b>El Niño, c\'est quoi ?</b> Tous les 2 à 7 ans, l\'eau du Pacifique équatorial se réchauffe anormalement sur des milliers de kilomètres. Ce réchauffement bouscule la météo de la planète : sécheresses en Australie et en Indonésie, pluies diluviennes au Pérou, et souvent une année record de chaleur mondiale dans la foulée. <b>La Niña</b> est l\'inverse, un refroidissement.<br><br><b>Le thermomètre.</b> Pour suivre El Niño, la NOAA mesure l\'écart à la normale de la température de l\'eau dans un rectangle au milieu du Pacifique, grand comme onze fois la France, appelé <b>Niño 3.4</b>. Tous les chiffres « °C » de cette page sont des écarts à la moyenne 1991-2020 : +1 °C veut dire « 1 degré plus chaud que d\'habitude à cette date ».</div>',
     '<div class="next"><b>What is El Niño?</b> Every 2 to 7 years, the water of the equatorial Pacific warms abnormally across thousands of kilometres. This warming disrupts weather worldwide: droughts in Australia and Indonesia, torrential rain in Peru, and often a record year for global heat close behind. <b>La Niña</b> is the opposite, a cooling.<br><br><b>The thermometer.</b> To track El Niño, NOAA measures the departure from normal of water temperature in a rectangle in the middle of the Pacific, about eleven times the size of France, called <b>Niño 3.4</b>. Every &laquo;&nbsp;°C&nbsp;&raquo; figure on this page is a departure from the 1991-2020 average: +1°C means &laquo;&nbsp;1 degree warmer than usual for that date&nbsp;&raquo;.</div>'),
    ('<b id="e4">+0.0 °C</b><span>Pacifique ouest</span>', '<b id="e4">+0.0 °C</b><span>Western Pacific</span>'),
    ('<b id="e3">+0.0 °C</b><span>Pacifique est</span>', '<b id="e3">+0.0 °C</b><span>Eastern Pacific</span>'),
    ('<b id="e12">+0.0 °C</b><span>Au large du Pérou</span>', '<b id="e12">+0.0 °C</b><span>Off the coast of Peru</span>'),
    ('<span id="eonilab">Moyenne officielle sur 3 mois</span>', '<span id="eonilab">3-month official average</span>'),
    ('<h2>Le thermomètre d\'El Niño sur un an</h2>', '<h2>The El Niño thermometer over the past year</h2>'),
    ('<p>Écart à la normale de l\'eau dans le rectangle Niño 3.4, mesuré par satellite. Au-dessus de la ligne rouge (+0,5 °C), on parle d\'El Niño ; sous la ligne bleue (−0,5 °C), de La Niña. Entre les deux, le Pacifique est neutre.</p>',
     '<p>Departure from normal of the water in the Niño 3.4 rectangle, measured by satellite. Above the red line (+0.5°C), it is called El Niño; below the blue line (−0.5°C), La Niña. In between, the Pacific is neutral.</p>'),
    ('<h2>La chaleur qui traverse le Pacifique</h2>', '<h2>The heat crossing the Pacific</h2>'),
    ('<p>Imaginez une bande d\'océan le long de l\'équateur, de l\'Indonésie (à gauche) jusqu\'au Pérou (à droite), près de 19 000 km. Chaque ligne horizontale est une photo de cette bande. On empile les photos : il y a un an en haut, aujourd\'hui en bas. <b>Quand le rouge s\'étale vers la droite en descendant, c\'est El Niño qui s\'installe.</b> Le cadre blanc est le rectangle du thermomètre.</p>',
     '<p>Picture a strip of ocean along the equator, from Indonesia (on the left) to Peru (on the right), nearly 19,000 km. Each horizontal line is a snapshot of that strip. The snapshots are stacked: one year ago at the top, today at the bottom. <b>When red spreads to the right as you go down, El Niño is taking hold.</b> The white frame marks the thermometer rectangle.</p>'),
    ('<span>eau plus froide</span><div class="bar"></div><span>plus chaude que la normale</span>',
     '<span>colder water</span><div class="bar"></div><span>warmer than normal</span>'),
    ('<h2>Depuis 1950</h2>', '<h2>Since 1950</h2>'),
    ('<p>La moyenne officielle du thermomètre sur trois mois glissants (indice « ONI » de la NOAA). Chaque barre est une saison : rouge pour El Niño, bleu pour La Niña. Un épisode n\'est officiel qu\'après cinq saisons d\'affilée au-delà du seuil. Les grands épisodes sont annotés.</p>',
     '<p>The thermometer\'s official three-month rolling average (NOAA\'s &laquo;&nbsp;ONI&nbsp;&raquo; index). Each bar is a season: red for El Niño, blue for La Niña. An episode is official only after five consecutive seasons beyond the threshold. Major episodes are labelled.</p>'),
    # footer
    ('Sources : mer, NOAA OISST v2.1 (0,25°, anomalie recalculée sur la base 1991-2020) ; terre, NOAA CPC Global Daily Temperature (0,5°, moyenne de Tmax et Tmin, base 1991-2020). Agrégées à 1° pour l\'affichage. Trait de côte Natural Earth. Indices et probabilités ENSO : NOAA CPC. Prévision mer : E.U. Copernicus Marine Service Information (GLO12). Prévision terres : ECMWF open data (CC BY 4.0). Prévisions calculées en ajoutant l\'évolution prévue par le modèle à l\'écart observé. Glace de mer : NSIDC Sea Ice Index v4 et OISST. Coraux : NOAA Coral Reef Watch. Derniers jours en statut préliminaire. Zones grises : pas de mesure (Antarctique, Groenland, trous de stations).',
     'Sources: ocean, NOAA OISST v2.1 (0.25°, anomaly recalculated on the 1991-2020 baseline); land, NOAA CPC Global Daily Temperature (0.5°, average of Tmax and Tmin, 1991-2020 baseline). Aggregated to 1° for display. Coastline: Natural Earth. ENSO indices and probabilities: NOAA CPC. Ocean forecast: E.U. Copernicus Marine Service Information (GLO12). Land forecast: ECMWF open data (CC BY 4.0). Forecasts computed by adding the model\'s projected change to the observed anomaly. Sea ice: NSIDC Sea Ice Index v4 and OISST. Corals: NOAA Coral Reef Watch. The most recent days are preliminary. Grey areas: no data (Antarctica, Greenland, station gaps).'),
    ('Climate Observer · conçu par <a href="https://oceandataconsulting.fr/en" target="_blank" rel="noopener">OceanData Consulting</a> · données NOAA, NSIDC, Copernicus Marine, ECMWF',
     'Climate Observer · built by <a href="https://oceandataconsulting.fr/en" target="_blank" rel="noopener">OceanData Consulting</a> · data: NOAA, NSIDC, Copernicus Marine, ECMWF'),
]


def build(lang):
    d = json.load(open(os.path.join(root, "data/build.json")))
    coast = open(os.path.join(root, "web/coast.min.json")).read()
    block = (f"const LANG=\"{lang}\";\n"
             f"const META={json.dumps(d['meta'])};\n"
             f'const B64="{d["ocean_b64"]}";\n'
             f"const COAST={coast};\n"
             f"const ENSO={json.dumps(d['enso'])};\n"
             f'const LB64="{d["land_b64"]}";\n'
             f"const SURV={json.dumps(d.get('surv') or {})};\n")
    tpl = open(os.path.join(root, "web/template.html")).read()
    assert "/*__DATA__*/" in tpl
    head, sep, rest = tpl.partition("<script>")
    assert sep, "template.html must contain <script>"

    if lang == "en":
        for fr, en in PAIRS_EN:
            assert fr in head, f"EN pair not found in static HTML: {fr!r}"
            head = head.replace(fr, en)
    else:
        head = head.replace("<!--LANGSWITCH-->", LANGSWITCH_FR)

    out = head + sep + rest.replace("/*__DATA__*/", block)
    out_path = os.path.join(root, "dist/index.html" if lang == "fr" else "dist/en/index.html")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w").write(out)
    print(out_path, round(len(out) / 1e6, 2), "Mo")


build("fr")
build("en")
shutil.copyfile(os.path.join(root, "web/og.png"), os.path.join(root, "dist/og.png"))
